"""db update

Revision ID: aca1cb18caa1
Revises: d5b3423b2968
Create Date: 2023-11-05 17:54:46.600762

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'aca1cb18caa1'
down_revision: Union[str, None] = 'd5b3423b2968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
